version: 0.3
phases:
  install:
    commands:
      - npm install
      - aws s3 sync . s3://deployment.bucket.des.moines
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml