AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function for Alexa
Resources:
  TestFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: ./