AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function for Alexa
Resources:
  TestFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Role: 
        AWSLambdaExecute
      Code:
        "S3Bucket": "deployment.bucket.des.moines"
        "S3Key": "625143f7f53d9de6f3d307ee8d06b28d.zip"
