AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda function for Alexa
Resources:
  TestFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      Role: arn:aws:iam::685813735696:role/AWSLambdaExecute
      Code:
        "S3Bucket": "deployment.bucket.des.moines"
        "S3Key": "src.zip"
        